spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:

            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/api/v1/auth/**

            - id: product-service
              uri: lb://product-service
              predicates:
                - Path=/api/v1/products/**,/internal/products/**

            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=/api/v1/orders/**

jwt:
  secret: 9d8b8d6d3d6e5b2f0c9a1e7f6d5c4b3a9e8f7d6c5b4a3f2e1d9c8b7a6f5e4d3c