server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/authdb
    username: myuser
    password: mypassword

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/

jwt:
  secret: 9d8b8d6d3d6e5b2f0c9a1e7f6d5c4b3a9e8f7d6c5b4a3f2e1d9c8b7a6f5e4d3c
  expiration: 86400000